set(${PROJECT_NAME}_MAJOR_VERSION_STR    "2018")
set(${PROJECT_NAME}_MINOR_VERSION_STR    "02")
set(${PROJECT_NAME}_REVISION_VERSION_STR "0")

set(${PROJECT_NAME}_VERSION_STR  "${${PROJECT_NAME}_MAJOR_VERSION_STR}.${${PROJECT_NAME}_MINOR_VERSION_STR}.${${PROJECT_NAME}_REVISION_VERSION_STR}")
